### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by SanskritFritz** [keenerd/pacmatic#18]
When I issue a `pacmatic -Syu` I get this output:

```
gzip: stdin: not in gzip format
gzip: stdin: not in gzip format
Recent ML chatter: 
Please enable CheckSpace in pacman.conf
:: Synchronizing package databases...
```

**Comment by shioyama** [comment]
It was there and then gone for me, now seems to be back again...

**Comment by dkambersky** [comment]
This happens when there's no ML archive to be downloaded yet (generally the first few days of a month). It's harmless, but could probably be fixed to fail silently, or notify the user about the absence, instead of this sorta cryptic error.
