### ISSUE TITLE
Minor nuisance: mailing lists not available yet depending on time every 1st of month

### ISSUE THREAD

**Issue by alcohol** [keenerd/pacmatic#27]
Every first of the month, when I use pacmatic, I get a bunch of

```
gzip: stdin: not in gzip format
```

thrown in my face.

It's because the feed it's trying to access (e.g. https://lists.archlinux.org/pipermail/arch-general/2015-September.txt.gz) is not accessible yet.

Would it be possible to first check if the url does not return a 404 before processing it?
If it does return a 404, fetch the one from last month instead or proceed with an empty string perhaps?

I saw that `--quiet` is being passed to **zcat**, but unfortunately the above is considered an error and not a warning, so it does not mute it.

**Comment by keenerd** [comment]
Something has changed on the server side of things.  (404 errors are now gzip encoded too?)  Anyway, the problem is gone.

**Comment by alcohol** [comment]
I cannot confirm this... ran into the same today.

```
rob ~ > sudo pacmatic -Syu

gzip: stdin: not in gzip format

gzip: stdin: not in gzip format
Recent ML chatter: 
:: Synchronizing package databases...

..snipped..

No pacnew files to update.
```

**Comment by Marcool04** [comment]
Sorry to comment on a closed issue, but this is indeed still happening…
````
$ pacmatic -Syu

gzip: stdin: not in gzip format

gzip: stdin: not in gzip format
Recent ML chatter:
:: Synchronizing package databases...
[…]
````
